name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential ccache
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer==1.5.0
          pip install setuptools

      - name: Build
        run: |
          # Aceasta este singura comandă necesară. 
          # Buildozer va descărca automat tot ce îi lipsește (SDK, NDK).
          buildozer android debug
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: scoalamaya-apk
          path: bin/*.apk
