name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            cmake libffi-dev libssl-dev wget tar \
            build-essential ccache

          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer==1.5.0
          pip install python-for-android==2024.01.21

      - name: Setup Android SDK PATH
        run: |
          echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Android SDK packages
        run: |
          export PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin

          yes | sdkmanager --licenses

          sdkmanager \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;25.2.9519653"

      - name: Build APK
        run: |
          cd Proiect

          
          sed -i 's/title = My Application/title = ScoalaMaya/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = scoalamaya/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.scoala/' buildozer.spec

          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,kv,atlas,ttf/' buildozer.spec

          sed -i 's/requirements = python3,kivy/requirements = python3==3.11.6,kivy==2.2.1/' buildozer.spec

          echo "android.api = 34" >> buildozer.spec
          echo "android.minapi = 24" >> buildozer.spec
          echo "android.sdk = 34" >> buildozer.spec
          echo "android.ndk = 25b" >> buildozer.spec
          echo "android.accept_sdk_license = True" >> buildozer.spec

          echo "android.sdk_path = /usr/local/lib/android/sdk" >> buildozer.spec
          echo "android.ndk_path = /usr/local/lib/android/sdk/ndk/25.2.9519653" >> buildozer.spec

          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: Proiect/bin/*.apk
