name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            zip \
            unzip \
            git \
            wget \
            openjdk-17-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33
          pip install buildozer

      - name: Setup Android SDK
        run: |
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools

          cd /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip

          unzip -o commandlinetools-linux-11076708_latest.zip

          mv cmdline-tools latest || true

          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/tools/bin

          ln -s /home/runner/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

          export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64

          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          export ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk

          export PATH=$JAVA_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses

          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;34.0.0"

      - name: Build APK
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
          ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk
          ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk

        run: |
          cd Proiect

          rm -rf .buildozer

          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: Proiect/bin/*.apk
